name: rdp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - boost-cpp=1.70.0=ha2d47e9_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - console_bridge=1.0.2=h924138e_1
  - empy=3.3.4=pyh9f0ad1d_1
  - expat=2.7.1=h6a678d5_0
  - gettext=0.21.0=h39681ba_1
  - gmock=1.17.0=h68a9205_0
  - gtest=1.17.0=h5f83a47_0
  - icu=58.2=he6710b0_3
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libunistring=1.3=hb25bd0a_0
  - libuv=1.48.0=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.10.4=hcbfbd50_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - python_abi=3.9=2_cp39
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - rhash=1.4.6=ha914fed_0
  - ros-catkin=0.7.17=py39hf149a3a_5
  - ros-conda-base=0.0.2=hcb32578_2
  - ros-conda-mutex=1.0=melodic
  - ros-cpp-common=0.6.12=h8b68381_0
  - ros-genmsg=0.5.12=py39hf149a3a_1
  - ros-genpy=0.6.8=py39hf149a3a_1
  - ros-geometry-msgs=1.12.7=py39hf149a3a_1
  - ros-message-runtime=0.4.12=he1b5a44_0
  - ros-roscpp-serialization=0.6.12=he1b5a44_0
  - ros-roscpp-traits=0.6.12=he1b5a44_0
  - ros-rostime=0.6.12=h8b68381_0
  - ros-std-msgs=0.5.12=py39hf149a3a_1
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.0.0
      - blinker==1.9.0
      - boto3==1.40.1
      - botocore==1.40.1
      - bson==0.5.10
      - catkin-pkg==1.1.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cmake==4.0.3
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.1.2
      - dash==3.2.0
      - datasets==4.0.0
      - debugpy==1.8.15
      - decorator==5.2.1
      - diffusers==0.34.0
      - dill==0.3.8
      - distro==1.9.0
      - docutils==0.22.3
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.116.1
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - ffmpy==0.6.1
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glcontext==3.0.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.74.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.3
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.30.0
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - iso8601==2.1.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lit==18.1.8
      - llvmlite==0.43.0
      - loguru==0.7.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moderngl==5.12.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - narwhals==2.0.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.60.0
      - numcodecs==0.12.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.11.1
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - peft==0.17.0
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pluggy==1.6.0
      - plyfile==1.1.2
      - pointnet2==0.0.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cli-interaction==0.3
      - pyarrow==21.0.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygame==2.6.1
      - pygments==2.19.2
      - pyinstrument==5.0.3
      - pymunk==7.1.0
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyrealsense2==2.56.5.9235
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyzmq==27.0.1
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - retrying==1.4.2
      - rich==14.1.0
      - rospkg==1.6.0
      - rpds-py==0.26.0
      - ruff==0.12.8
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scikit-video==1.1.11
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.34.1
      - serial==0.0.97
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.47.2
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.19
      - tokenizers==0.21.4
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.54.1
      - transforms3d==0.4.2
      - trimesh==4.7.1
      - triton==3.0.0
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - utils3d==0.0.2
      - uvicorn==0.35.0
      - wandb==0.21.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xxhash==3.5.0
      - yarl==1.20.1
      - zarr==2.18.2
      - zipp==3.23.0
prefix: /root/miniconda3/envs/rdp
